version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: "none"
  exclusions:
    paths:
      - ".*\\.gen\\.go"
      - "fixtures\\.go"

  enable:
    - asciicheck
    - cyclop
    - dogsled
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - goconst
    - gocritic
    - godot
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nlreturn
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace

  settings:
    cyclop:
      max-complexity: 9
    funlen:
      statements: 65
    nestif:
      min-complexity: 5
    nlreturn:
      block-size: 3

formatters:
  exclusions:
    paths:
      - ".*\\.gen\\.go"
      - "fixtures\\.go"

  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports

  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/selectel/mks-go/v2)
