with-expecter: True
filename: "mock_{{.InterfaceName}}.go"
dir: "{{.InterfaceDir}}/mocks"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
all: True
disable-version-string: True
issue-845-fix: True
resolve-type-alias: False
packages:
  github.com/selectel/mks-go/v2:
    config:
      recursive: True
