sudo: false
language: go
install:
  - go get github.com/mattn/goveralls
  - go get github.com/wadey/gocovmerge
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.3
go:
  - "1.13"
  - "1.14"
script:
  - make tests
after_success:
- $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
