// Package mksclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package mksclient

import (
	"time"
)

const (
	Iam_token_project_scopedScopes = "iam_token_project_scoped.Scopes"
)

// Defines values for ClusterClusterType.
const (
	ClusterClusterTypeBASIC                   ClusterClusterType = "BASIC"
	ClusterClusterTypeHIGHAVAILABILITY        ClusterClusterType = "HIGH_AVAILABILITY"
	ClusterClusterTypeHIGHAVAILABILITYMULTIAZ ClusterClusterType = "HIGH_AVAILABILITY_MULTI_AZ"
)

// Valid indicates whether the value is a known member of the ClusterClusterType enum.
func (e ClusterClusterType) Valid() bool {
	switch e {
	case ClusterClusterTypeBASIC:
		return true
	case ClusterClusterTypeHIGHAVAILABILITY:
		return true
	case ClusterClusterTypeHIGHAVAILABILITYMULTIAZ:
		return true
	default:
		return false
	}
}

// Defines values for ClusterCniType.
const (
	ClusterCniTypeCALICO ClusterCniType = "CALICO"
	ClusterCniTypeCILIUM ClusterCniType = "CILIUM"
)

// Valid indicates whether the value is a known member of the ClusterCniType enum.
func (e ClusterCniType) Valid() bool {
	switch e {
	case ClusterCniTypeCALICO:
		return true
	case ClusterCniTypeCILIUM:
		return true
	default:
		return false
	}
}

// Defines values for ClusterNetworkType.
const (
	ClusterNetworkTypeL3VPN    ClusterNetworkType = "L3VPN"
	ClusterNetworkTypeSTANDARD ClusterNetworkType = "STANDARD"
)

// Valid indicates whether the value is a known member of the ClusterNetworkType enum.
func (e ClusterNetworkType) Valid() bool {
	switch e {
	case ClusterNetworkTypeL3VPN:
		return true
	case ClusterNetworkTypeSTANDARD:
		return true
	default:
		return false
	}
}

// Defines values for ClusterStatus.
const (
	ClusterStatusACTIVE   ClusterStatus = "ACTIVE"
	ClusterStatusCREATING ClusterStatus = "CREATING"
	ClusterStatusDELETED  ClusterStatus = "DELETED"
	ClusterStatusERROR    ClusterStatus = "ERROR"
)

// Valid indicates whether the value is a known member of the ClusterStatus enum.
func (e ClusterStatus) Valid() bool {
	switch e {
	case ClusterStatusACTIVE:
		return true
	case ClusterStatusCREATING:
		return true
	case ClusterStatusDELETED:
		return true
	case ClusterStatusERROR:
		return true
	default:
		return false
	}
}

// Defines values for ClusterCreateStructClusterType.
const (
	ClusterCreateStructClusterTypeBASIC                   ClusterCreateStructClusterType = "BASIC"
	ClusterCreateStructClusterTypeHIGHAVAILABILITY        ClusterCreateStructClusterType = "HIGH_AVAILABILITY"
	ClusterCreateStructClusterTypeHIGHAVAILABILITYMULTIAZ ClusterCreateStructClusterType = "HIGH_AVAILABILITY_MULTI_AZ"
)

// Valid indicates whether the value is a known member of the ClusterCreateStructClusterType enum.
func (e ClusterCreateStructClusterType) Valid() bool {
	switch e {
	case ClusterCreateStructClusterTypeBASIC:
		return true
	case ClusterCreateStructClusterTypeHIGHAVAILABILITY:
		return true
	case ClusterCreateStructClusterTypeHIGHAVAILABILITYMULTIAZ:
		return true
	default:
		return false
	}
}

// Defines values for ClusterDetailedClusterType.
const (
	BASIC                   ClusterDetailedClusterType = "BASIC"
	HIGHAVAILABILITY        ClusterDetailedClusterType = "HIGH_AVAILABILITY"
	HIGHAVAILABILITYMULTIAZ ClusterDetailedClusterType = "HIGH_AVAILABILITY_MULTI_AZ"
)

// Valid indicates whether the value is a known member of the ClusterDetailedClusterType enum.
func (e ClusterDetailedClusterType) Valid() bool {
	switch e {
	case BASIC:
		return true
	case HIGHAVAILABILITY:
		return true
	case HIGHAVAILABILITYMULTIAZ:
		return true
	default:
		return false
	}
}

// Defines values for ClusterDetailedCniType.
const (
	ClusterDetailedCniTypeCALICO ClusterDetailedCniType = "CALICO"
	ClusterDetailedCniTypeCILIUM ClusterDetailedCniType = "CILIUM"
)

// Valid indicates whether the value is a known member of the ClusterDetailedCniType enum.
func (e ClusterDetailedCniType) Valid() bool {
	switch e {
	case ClusterDetailedCniTypeCALICO:
		return true
	case ClusterDetailedCniTypeCILIUM:
		return true
	default:
		return false
	}
}

// Defines values for ClusterDetailedNetworkType.
const (
	ClusterDetailedNetworkTypeL3VPN    ClusterDetailedNetworkType = "L3VPN"
	ClusterDetailedNetworkTypeSTANDARD ClusterDetailedNetworkType = "STANDARD"
)

// Valid indicates whether the value is a known member of the ClusterDetailedNetworkType enum.
func (e ClusterDetailedNetworkType) Valid() bool {
	switch e {
	case ClusterDetailedNetworkTypeL3VPN:
		return true
	case ClusterDetailedNetworkTypeSTANDARD:
		return true
	default:
		return false
	}
}

// Defines values for ClusterDetailedStatus.
const (
	ClusterDetailedStatusACTIVE                             ClusterDetailedStatus = "ACTIVE"
	ClusterDetailedStatusERROR                              ClusterDetailedStatus = "ERROR"
	ClusterDetailedStatusMAINTENANCE                        ClusterDetailedStatus = "MAINTENANCE"
	ClusterDetailedStatusPENDINGCREATE                      ClusterDetailedStatus = "PENDING_CREATE"
	ClusterDetailedStatusPENDINGDELETE                      ClusterDetailedStatus = "PENDING_DELETE"
	ClusterDetailedStatusPENDINGNODEREINSTALL               ClusterDetailedStatus = "PENDING_NODE_REINSTALL"
	ClusterDetailedStatusPENDINGNODESUNSHELVE               ClusterDetailedStatus = "PENDING_NODES_UNSHELVE"
	ClusterDetailedStatusPENDINGREINSTALLMASTERS            ClusterDetailedStatus = "PENDING_REINSTALL_MASTERS"
	ClusterDetailedStatusPENDINGRESIZE                      ClusterDetailedStatus = "PENDING_RESIZE"
	ClusterDetailedStatusPENDINGROTATECERTS                 ClusterDetailedStatus = "PENDING_ROTATE_CERTS"
	ClusterDetailedStatusPENDINGUPDATE                      ClusterDetailedStatus = "PENDING_UPDATE"
	ClusterDetailedStatusPENDINGUPDATENODEGROUP             ClusterDetailedStatus = "PENDING_UPDATE_NODEGROUP"
	ClusterDetailedStatusPENDINGUPDATEREGISTRIESINTEGRATION ClusterDetailedStatus = "PENDING_UPDATE_REGISTRIES_INTEGRATION"
	ClusterDetailedStatusPENDINGUPGRADE                     ClusterDetailedStatus = "PENDING_UPGRADE"
	ClusterDetailedStatusPENDINGUPGRADECLUSTERCONFIGURATION ClusterDetailedStatus = "PENDING_UPGRADE_CLUSTER_CONFIGURATION"
	ClusterDetailedStatusPENDINGUPGRADEMASTERSCONFIGURATION ClusterDetailedStatus = "PENDING_UPGRADE_MASTERS_CONFIGURATION"
	ClusterDetailedStatusPENDINGUPGRADEMINORVERSION         ClusterDetailedStatus = "PENDING_UPGRADE_MINOR_VERSION"
	ClusterDetailedStatusPENDINGUPGRADEPATCHVERSION         ClusterDetailedStatus = "PENDING_UPGRADE_PATCH_VERSION"
)

// Valid indicates whether the value is a known member of the ClusterDetailedStatus enum.
func (e ClusterDetailedStatus) Valid() bool {
	switch e {
	case ClusterDetailedStatusACTIVE:
		return true
	case ClusterDetailedStatusERROR:
		return true
	case ClusterDetailedStatusMAINTENANCE:
		return true
	case ClusterDetailedStatusPENDINGCREATE:
		return true
	case ClusterDetailedStatusPENDINGDELETE:
		return true
	case ClusterDetailedStatusPENDINGNODEREINSTALL:
		return true
	case ClusterDetailedStatusPENDINGNODESUNSHELVE:
		return true
	case ClusterDetailedStatusPENDINGREINSTALLMASTERS:
		return true
	case ClusterDetailedStatusPENDINGRESIZE:
		return true
	case ClusterDetailedStatusPENDINGROTATECERTS:
		return true
	case ClusterDetailedStatusPENDINGUPDATE:
		return true
	case ClusterDetailedStatusPENDINGUPDATENODEGROUP:
		return true
	case ClusterDetailedStatusPENDINGUPDATEREGISTRIESINTEGRATION:
		return true
	case ClusterDetailedStatusPENDINGUPGRADE:
		return true
	case ClusterDetailedStatusPENDINGUPGRADECLUSTERCONFIGURATION:
		return true
	case ClusterDetailedStatusPENDINGUPGRADEMASTERSCONFIGURATION:
		return true
	case ClusterDetailedStatusPENDINGUPGRADEMINORVERSION:
		return true
	case ClusterDetailedStatusPENDINGUPGRADEPATCHVERSION:
		return true
	default:
		return false
	}
}

// Defines values for DedicatedNodegroupConfigCurrency.
const (
	Bonus DedicatedNodegroupConfigCurrency = "bonus"
	Main  DedicatedNodegroupConfigCurrency = "main"
)

// Valid indicates whether the value is a known member of the DedicatedNodegroupConfigCurrency enum.
func (e DedicatedNodegroupConfigCurrency) Valid() bool {
	switch e {
	case Bonus:
		return true
	case Main:
		return true
	default:
		return false
	}
}

// Defines values for NodegroupDetailedNodegroupType.
const (
	NodegroupDetailedNodegroupTypeDEDICATED    NodegroupDetailedNodegroupType = "DEDICATED"
	NodegroupDetailedNodegroupTypeDEDICATEDGPU NodegroupDetailedNodegroupType = "DEDICATED_GPU"
	NodegroupDetailedNodegroupTypeGPU          NodegroupDetailedNodegroupType = "GPU"
	NodegroupDetailedNodegroupTypeSTANDARD     NodegroupDetailedNodegroupType = "STANDARD"
)

// Valid indicates whether the value is a known member of the NodegroupDetailedNodegroupType enum.
func (e NodegroupDetailedNodegroupType) Valid() bool {
	switch e {
	case NodegroupDetailedNodegroupTypeDEDICATED:
		return true
	case NodegroupDetailedNodegroupTypeDEDICATEDGPU:
		return true
	case NodegroupDetailedNodegroupTypeGPU:
		return true
	case NodegroupDetailedNodegroupTypeSTANDARD:
		return true
	default:
		return false
	}
}

// Defines values for NodegroupDetailedStatus.
const (
	NodegroupDetailedStatusACTIVE               NodegroupDetailedStatus = "ACTIVE"
	NodegroupDetailedStatusERROR                NodegroupDetailedStatus = "ERROR"
	NodegroupDetailedStatusPENDINGCREATE        NodegroupDetailedStatus = "PENDING_CREATE"
	NodegroupDetailedStatusPENDINGDELETE        NodegroupDetailedStatus = "PENDING_DELETE"
	NodegroupDetailedStatusPENDINGNODEREINSTALL NodegroupDetailedStatus = "PENDING_NODE_REINSTALL"
	NodegroupDetailedStatusPENDINGNODESUNSHELVE NodegroupDetailedStatus = "PENDING_NODES_UNSHELVE"
	NodegroupDetailedStatusPENDINGSCALEDOWN     NodegroupDetailedStatus = "PENDING_SCALE_DOWN"
	NodegroupDetailedStatusPENDINGSCALEUP       NodegroupDetailedStatus = "PENDING_SCALE_UP"
	NodegroupDetailedStatusPENDINGUPDATE        NodegroupDetailedStatus = "PENDING_UPDATE"
)

// Valid indicates whether the value is a known member of the NodegroupDetailedStatus enum.
func (e NodegroupDetailedStatus) Valid() bool {
	switch e {
	case NodegroupDetailedStatusACTIVE:
		return true
	case NodegroupDetailedStatusERROR:
		return true
	case NodegroupDetailedStatusPENDINGCREATE:
		return true
	case NodegroupDetailedStatusPENDINGDELETE:
		return true
	case NodegroupDetailedStatusPENDINGNODEREINSTALL:
		return true
	case NodegroupDetailedStatusPENDINGNODESUNSHELVE:
		return true
	case NodegroupDetailedStatusPENDINGSCALEDOWN:
		return true
	case NodegroupDetailedStatusPENDINGSCALEUP:
		return true
	case NodegroupDetailedStatusPENDINGUPDATE:
		return true
	default:
		return false
	}
}

// Defines values for NodegroupInfoNodegroupType.
const (
	NodegroupInfoNodegroupTypeDEDICATED    NodegroupInfoNodegroupType = "DEDICATED"
	NodegroupInfoNodegroupTypeDEDICATEDGPU NodegroupInfoNodegroupType = "DEDICATED_GPU"
	NodegroupInfoNodegroupTypeGPU          NodegroupInfoNodegroupType = "GPU"
	NodegroupInfoNodegroupTypeSTANDARD     NodegroupInfoNodegroupType = "STANDARD"
)

// Valid indicates whether the value is a known member of the NodegroupInfoNodegroupType enum.
func (e NodegroupInfoNodegroupType) Valid() bool {
	switch e {
	case NodegroupInfoNodegroupTypeDEDICATED:
		return true
	case NodegroupInfoNodegroupTypeDEDICATEDGPU:
		return true
	case NodegroupInfoNodegroupTypeGPU:
		return true
	case NodegroupInfoNodegroupTypeSTANDARD:
		return true
	default:
		return false
	}
}

// Defines values for NodegroupInfoStatus.
const (
	NodegroupInfoStatusACTIVE               NodegroupInfoStatus = "ACTIVE"
	NodegroupInfoStatusERROR                NodegroupInfoStatus = "ERROR"
	NodegroupInfoStatusPENDINGCREATE        NodegroupInfoStatus = "PENDING_CREATE"
	NodegroupInfoStatusPENDINGDELETE        NodegroupInfoStatus = "PENDING_DELETE"
	NodegroupInfoStatusPENDINGNODEREINSTALL NodegroupInfoStatus = "PENDING_NODE_REINSTALL"
	NodegroupInfoStatusPENDINGNODESUNSHELVE NodegroupInfoStatus = "PENDING_NODES_UNSHELVE"
	NodegroupInfoStatusPENDINGSCALEDOWN     NodegroupInfoStatus = "PENDING_SCALE_DOWN"
	NodegroupInfoStatusPENDINGSCALEUP       NodegroupInfoStatus = "PENDING_SCALE_UP"
	NodegroupInfoStatusPENDINGUPDATE        NodegroupInfoStatus = "PENDING_UPDATE"
)

// Valid indicates whether the value is a known member of the NodegroupInfoStatus enum.
func (e NodegroupInfoStatus) Valid() bool {
	switch e {
	case NodegroupInfoStatusACTIVE:
		return true
	case NodegroupInfoStatusERROR:
		return true
	case NodegroupInfoStatusPENDINGCREATE:
		return true
	case NodegroupInfoStatusPENDINGDELETE:
		return true
	case NodegroupInfoStatusPENDINGNODEREINSTALL:
		return true
	case NodegroupInfoStatusPENDINGNODESUNSHELVE:
		return true
	case NodegroupInfoStatusPENDINGSCALEDOWN:
		return true
	case NodegroupInfoStatusPENDINGSCALEUP:
		return true
	case NodegroupInfoStatusPENDINGUPDATE:
		return true
	default:
		return false
	}
}

// Defines values for NodegroupListItemNodegroupType.
const (
	DEDICATED    NodegroupListItemNodegroupType = "DEDICATED"
	DEDICATEDGPU NodegroupListItemNodegroupType = "DEDICATED_GPU"
	GPU          NodegroupListItemNodegroupType = "GPU"
	STANDARD     NodegroupListItemNodegroupType = "STANDARD"
)

// Valid indicates whether the value is a known member of the NodegroupListItemNodegroupType enum.
func (e NodegroupListItemNodegroupType) Valid() bool {
	switch e {
	case DEDICATED:
		return true
	case DEDICATEDGPU:
		return true
	case GPU:
		return true
	case STANDARD:
		return true
	default:
		return false
	}
}

// Defines values for NodegroupListItemStatus.
const (
	NodegroupListItemStatusACTIVE               NodegroupListItemStatus = "ACTIVE"
	NodegroupListItemStatusERROR                NodegroupListItemStatus = "ERROR"
	NodegroupListItemStatusPENDINGCREATE        NodegroupListItemStatus = "PENDING_CREATE"
	NodegroupListItemStatusPENDINGDELETE        NodegroupListItemStatus = "PENDING_DELETE"
	NodegroupListItemStatusPENDINGNODEREINSTALL NodegroupListItemStatus = "PENDING_NODE_REINSTALL"
	NodegroupListItemStatusPENDINGNODESUNSHELVE NodegroupListItemStatus = "PENDING_NODES_UNSHELVE"
	NodegroupListItemStatusPENDINGSCALEDOWN     NodegroupListItemStatus = "PENDING_SCALE_DOWN"
	NodegroupListItemStatusPENDINGSCALEUP       NodegroupListItemStatus = "PENDING_SCALE_UP"
	NodegroupListItemStatusPENDINGUPDATE        NodegroupListItemStatus = "PENDING_UPDATE"
)

// Valid indicates whether the value is a known member of the NodegroupListItemStatus enum.
func (e NodegroupListItemStatus) Valid() bool {
	switch e {
	case NodegroupListItemStatusACTIVE:
		return true
	case NodegroupListItemStatusERROR:
		return true
	case NodegroupListItemStatusPENDINGCREATE:
		return true
	case NodegroupListItemStatusPENDINGDELETE:
		return true
	case NodegroupListItemStatusPENDINGNODEREINSTALL:
		return true
	case NodegroupListItemStatusPENDINGNODESUNSHELVE:
		return true
	case NodegroupListItemStatusPENDINGSCALEDOWN:
		return true
	case NodegroupListItemStatusPENDINGSCALEUP:
		return true
	case NodegroupListItemStatusPENDINGUPDATE:
		return true
	default:
		return false
	}
}

// Defines values for NodegroupTaintEffect.
const (
	NoExecute        NodegroupTaintEffect = "NoExecute"
	NoSchedule       NodegroupTaintEffect = "NoSchedule"
	PreferNoSchedule NodegroupTaintEffect = "PreferNoSchedule"
)

// Valid indicates whether the value is a known member of the NodegroupTaintEffect enum.
func (e NodegroupTaintEffect) Valid() bool {
	switch e {
	case NoExecute:
		return true
	case NoSchedule:
		return true
	case PreferNoSchedule:
		return true
	default:
		return false
	}
}

// Defines values for NodegroupUpdateStrategyMethod.
const (
	InPlace NodegroupUpdateStrategyMethod = "in_place"
	Replace NodegroupUpdateStrategyMethod = "replace"
)

// Valid indicates whether the value is a known member of the NodegroupUpdateStrategyMethod enum.
func (e NodegroupUpdateStrategyMethod) Valid() bool {
	switch e {
	case InPlace:
		return true
	case Replace:
		return true
	default:
		return false
	}
}

// Defines values for RegistriesIntegrationStatus.
const (
	RegistriesIntegrationStatusACTIVE        RegistriesIntegrationStatus = "ACTIVE"
	RegistriesIntegrationStatusDELETED       RegistriesIntegrationStatus = "DELETED"
	RegistriesIntegrationStatusERROR         RegistriesIntegrationStatus = "ERROR"
	RegistriesIntegrationStatusINACTIVE      RegistriesIntegrationStatus = "INACTIVE"
	RegistriesIntegrationStatusPENDINGCREATE RegistriesIntegrationStatus = "PENDING_CREATE"
	RegistriesIntegrationStatusPENDINGDELETE RegistriesIntegrationStatus = "PENDING_DELETE"
	RegistriesIntegrationStatusPENDINGUPDATE RegistriesIntegrationStatus = "PENDING_UPDATE"
	RegistriesIntegrationStatusUNKNOWN       RegistriesIntegrationStatus = "UNKNOWN"
)

// Valid indicates whether the value is a known member of the RegistriesIntegrationStatus enum.
func (e RegistriesIntegrationStatus) Valid() bool {
	switch e {
	case RegistriesIntegrationStatusACTIVE:
		return true
	case RegistriesIntegrationStatusDELETED:
		return true
	case RegistriesIntegrationStatusERROR:
		return true
	case RegistriesIntegrationStatusINACTIVE:
		return true
	case RegistriesIntegrationStatusPENDINGCREATE:
		return true
	case RegistriesIntegrationStatusPENDINGDELETE:
		return true
	case RegistriesIntegrationStatusPENDINGUPDATE:
		return true
	case RegistriesIntegrationStatusUNKNOWN:
		return true
	default:
		return false
	}
}

// Defines values for TaskStatus.
const (
	CANCELED   TaskStatus = "CANCELED"
	DONE       TaskStatus = "DONE"
	ERROR      TaskStatus = "ERROR"
	INPROGRESS TaskStatus = "IN_PROGRESS"
	INQUEUE    TaskStatus = "IN_QUEUE"
)

// Valid indicates whether the value is a known member of the TaskStatus enum.
func (e TaskStatus) Valid() bool {
	switch e {
	case CANCELED:
		return true
	case DONE:
		return true
	case ERROR:
		return true
	case INPROGRESS:
		return true
	case INQUEUE:
		return true
	default:
		return false
	}
}

// Defines values for Lang.
const (
	LangEn Lang = "en"
	LangRu Lang = "ru"
)

// Valid indicates whether the value is a known member of the Lang enum.
func (e Lang) Valid() bool {
	switch e {
	case LangEn:
		return true
	case LangRu:
		return true
	default:
		return false
	}
}

// Defines values for GetClusterActionsV2ParamsLang.
const (
	GetClusterActionsV2ParamsLangEn GetClusterActionsV2ParamsLang = "en"
	GetClusterActionsV2ParamsLangRu GetClusterActionsV2ParamsLang = "ru"
)

// Valid indicates whether the value is a known member of the GetClusterActionsV2ParamsLang enum.
func (e GetClusterActionsV2ParamsLang) Valid() bool {
	switch e {
	case GetClusterActionsV2ParamsLangEn:
		return true
	case GetClusterActionsV2ParamsLangRu:
		return true
	default:
		return false
	}
}

// Defines values for GetNodegroupActionsV2ParamsLang.
const (
	GetNodegroupActionsV2ParamsLangEn GetNodegroupActionsV2ParamsLang = "en"
	GetNodegroupActionsV2ParamsLangRu GetNodegroupActionsV2ParamsLang = "ru"
)

// Valid indicates whether the value is a known member of the GetNodegroupActionsV2ParamsLang enum.
func (e GetNodegroupActionsV2ParamsLang) Valid() bool {
	switch e {
	case GetNodegroupActionsV2ParamsLangEn:
		return true
	case GetNodegroupActionsV2ParamsLangRu:
		return true
	default:
		return false
	}
}

// Defines values for ListLogComponentsV2ParamsLang.
const (
	ListLogComponentsV2ParamsLangEn ListLogComponentsV2ParamsLang = "en"
	ListLogComponentsV2ParamsLangRu ListLogComponentsV2ParamsLang = "ru"
)

// Valid indicates whether the value is a known member of the ListLogComponentsV2ParamsLang enum.
func (e ListLogComponentsV2ParamsLang) Valid() bool {
	switch e {
	case ListLogComponentsV2ParamsLangEn:
		return true
	case ListLogComponentsV2ParamsLangRu:
		return true
	default:
		return false
	}
}

// Action defines model for Action.
type Action struct {
	// Available Available set true when action is available for current object.
	Available bool `json:"available"`

	// Reason Reason explains why available is false, skipped when available is true.
	Reason string `json:"reason,omitempty"`
}

// AdmissionControllersList List of available admission controllers.
type AdmissionControllersList struct {
	AdmissionControllers *[]AvailableAdmissionControllers `json:"admission_controllers,omitempty"`
}

// AuditLogs defines model for AuditLogs.
type AuditLogs struct {
	// Enabled If `true`, Kubernetes audit logs are collected.
	// and pushed into the SIEM system (e.g. logstash).
	// False by default.
	Enabled bool `json:"enabled"`

	// SecretName Contains the name of the Kubernetes secret in namespace kube-system with credentials of the SIEM system where logs should be pushed. Fields of the secret: host, port, username (optional), password (optional), ca.crt (optional). This field is optional. By default, used mks-audit-logs is used. Secret name should be as a DNS subdomain name as defined in RFC 1123. [More Information.](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names)
	SecretName string `json:"secret_name"`
}

// AvailableAdmissionControllers Detailed info about available admission controllers
// for every k8s minor version.
type AvailableAdmissionControllers struct {
	// KubeVersionMinor Kubernetes minor version.
	KubeVersionMinor *string `json:"kube_version_minor,omitempty"`

	// Names List of available admission controllers.
	Names *OptionNamesAC `json:"names,omitempty"`
}

// AvailableFeatureGates Detailed info about available feature gates
// for every k8s minor version.
type AvailableFeatureGates struct {
	// KubeVersionMinor Kubernetes minor version.
	KubeVersionMinor *string `json:"kube_version_minor,omitempty"`

	// Names List of available feature gate names.
	Names *OptionNamesFG `json:"names,omitempty"`
}

// CNICiliumSettings Settings for Cilium CNI if this CNI was chosen as "cni_type".
// Otherwise settings will be ignored.
type CNICiliumSettings struct {
	// EnvoyDaemonset Enables Envoy DaemonSet for Cilium CNI.
	EnvoyDaemonset *bool `json:"envoy_daemonset,omitempty"`

	// HubbleRelay Enables hubble relay for Cilium CNI.
	HubbleRelay *bool `json:"hubble_relay,omitempty"`
}

// CloudNodegroupConfig Configuration of cloud-based node groups.
type CloudNodegroupConfig struct {
	// AffinityPolicy An optional parameter to tune nodes affinity.
	AffinityPolicy string `json:"affinity_policy,omitempty"`

	// Cpus CPU count for each node.
	// It can be omitted only when `flavor_id` is set.
	Cpus int64 `json:"cpus,omitempty"`

	// FlavorId Contains reference to a pre-created flavor. It can be omitted in most cases.
	FlavorId string `json:"flavor_id,omitempty"`

	// KeypairName Name of an SSH key added to all nodes.
	KeypairName string `json:"keypair_name,omitempty"`

	// LocalVolume Indicates whether nodes will use a local volume.
	LocalVolume bool `json:"local_volume,omitempty"`

	// RamMb RAM count in MB for each node.
	// It can be omitted only when `flavor_id` is set.
	RamMb int64 `json:"ram_mb,omitempty"`

	// VolumeGb Volume size in GB for each node.
	// It can be omitted only when `flavor_id` is set and volume is local.
	VolumeGb int64 `json:"volume_gb,omitempty"`

	// VolumeType Block storage volume type for each node.
	// It can be omitted only in cases when `flavor_id` is set and `local_volume` is true.
	VolumeType string `json:"volume_type,omitempty"`
}

// CloudNodegroupConfigInfo Configuration of cloud-based node groups in response.
type CloudNodegroupConfigInfo struct {
	// AffinityPolicy An optional parameter to tune nodes affinity.
	AffinityPolicy string `json:"affinity_policy,omitempty"`

	// FlavorId Contains reference to a pre-created flavor. It can be omitted in most cases.
	FlavorId string `json:"flavor_id,omitempty"`

	// KeypairName Contains name of the SSH key that will be added to all nodes.
	KeypairName string `json:"keypair_name,omitempty"`

	// LocalVolume Indicates whether nodes will use a local volume.
	LocalVolume bool `json:"local_volume,omitempty"`

	// VolumeGb Volume size in GB for each node.
	// It can be omitted only in cases when `flavor_id` is set and `local_volume` is true.
	VolumeGb int64 `json:"volume_gb,omitempty"`

	// VolumeType Block storage volume type for each node.
	// It can be omitted only in cases when `flavor_id` is set and `local_volume` is true.
	VolumeType string `json:"volume_type,omitempty"`
}

// Cluster Provides information about cluster.
type Cluster struct {
	// Basic Specifies that cluster has only a single master and that control plane is not in highly available mode.
	Basic bool `json:"basic"`

	// ClusterType The type of the cluster.
	ClusterType ClusterClusterType `json:"cluster_type"`

	// CniType CNI type represents type of CNI which is used in cluster.
	CniType ClusterCniType `json:"cni_type"`

	// CreatedAt Timestamp in UTC timezone of when the cluster has been created.
	CreatedAt time.Time `json:"created_at"`

	// EnableAutorepair Reflects whether worker nodes are allowed to be reinstalled automatically in case of their unavailability or unhealthiness.
	EnableAutorepair bool `json:"enable_autorepair"`

	// EnablePatchVersionAutoUpgrade Specifies whether the Kubernetes version of the cluster is allowed to be upgraded automatically.
	EnablePatchVersionAutoUpgrade bool `json:"enable_patch_version_auto_upgrade"`

	// Id Unique identifier of the cluster.
	Id string `json:"id"`

	// KubeApiIp The IP of the Kubernetes API.
	KubeApiIp string `json:"kube_api_ip"`

	// KubeVersion The current Kubernetes version of the cluster.
	KubeVersion string `json:"kube_version"`

	// KubernetesOptions Additional k8s options such as pod security policy,
	// feature gates, etc.
	KubernetesOptions KubernetesOptions `json:"kubernetes_options"`

	// Name The name of the cluster.
	Name string `json:"name"`

	// NetworkId Contains reference to the network of the cluster.
	NetworkId string `json:"network_id"`

	// NetworkType Type of network l3vpn or default.
	NetworkType ClusterNetworkType `json:"network_type"`

	// Pool Pool represents the pool where the cluster master nodes are located.
	Pool string `json:"pool"`

	// PrivateKubeApi Whether kube API is available from the Internet or not.
	PrivateKubeApi bool `json:"private_kube_api"`

	// ProjectId Contains reference to the project of the cluster.
	ProjectId string `json:"project_id"`

	// Status Current status of the cluster.
	Status ClusterStatus `json:"status"`

	// SubnetId Contains reference to the subnet of the cluster.
	SubnetId string `json:"subnet_id"`

	// UpdatedAt Timestamp in UTC timezone of when the cluster has been updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// ClusterClusterType The type of the cluster.
type ClusterClusterType string

// ClusterCniType CNI type represents type of CNI which is used in cluster.
type ClusterCniType string

// ClusterNetworkType Type of network l3vpn or default.
type ClusterNetworkType string

// ClusterStatus Current status of the cluster.
type ClusterStatus string

// ClusterActions defines model for ClusterActions.
type ClusterActions struct {
	AddNodegroup                Action `json:"add_nodegroup"`
	Delete                      Action `json:"delete"`
	GetKubeconfig               Action `json:"get_kubeconfig"`
	RotateCertificates          Action `json:"rotate_certificates"`
	UpdateAuditLogs             Action `json:"update_audit_logs"`
	UpdateAutoRepair            Action `json:"update_auto_repair"`
	UpdateMaintenanceStart      Action `json:"update_maintenance_start"`
	UpdateOidc                  Action `json:"update_oidc"`
	UpdatePatchAutoUpgrade      Action `json:"update_patch_auto_upgrade"`
	UpdateRegistriesIntegration Action `json:"update_registries_integration"`
	UpgradeMinorVersion         Action `json:"upgrade_minor_version"`
	UpgradePatchVersion         Action `json:"upgrade_patch_version"`
}

// ClusterActionsResp Available actions of the cluster.
type ClusterActionsResp struct {
	Actions *ClusterActions `json:"actions,omitempty"`
}

// ClusterCreateBody ClusterCreateBody
// represents body content.
type ClusterCreateBody struct {
	Cluster *ClusterCreateStruct `json:"cluster,omitempty"`
}

// ClusterCreateStruct defines model for ClusterCreateStruct.
type ClusterCreateStruct struct {
	// Basic Basic specifies that only a single zonal master will be created.
	// It is needed if a highly available control plane is not required.
	// False by default.
	Basic           bool   `json:"basic"`
	CloudSubnetCidr string `json:"cloud_subnet_cidr,omitempty"`

	// ClusterType The type of the cluster. If not specified,
	// defaults based on the 'basic' field: basic=true → BASIC,
	// basic=false → HIGH_AVAILABILITY. For HIGH_AVAILABILITY_MULTI_AZ
	// clusters this field is required.
	ClusterType *ClusterCreateStructClusterType `json:"cluster_type,omitempty"`

	// CniCiliumSettings Settings for Cilium CNI if this CNI was chosen as "cni_type".
	// Otherwise settings will be ignored.
	CniCiliumSettings *CNICiliumSettings `json:"cni_cilium_settings,omitempty"`

	// CniType CNI type represents type of CNI which will be used in cluster.
	// Supported CNI types are CALICO and CILIUM. CALICO by default.
	CniType *string `json:"cni_type,omitempty"`

	// EnableAutorepair EnableAutorepair reflects whether worker nodes are allowed to be reinstalled  automatically in case of their unavailability or unhealthiness.
	EnableAutorepair *bool `json:"enable_autorepair,omitempty"`

	// EnablePatchVersionAutoUpgrade EnablePatchVersionAutoUpgrade specifies whether the Kubernetes version of the cluster is allowed to be upgraded
	// automatically.
	// Enabled by default for regional clusters and disabled for zonal clusters.
	EnablePatchVersionAutoUpgrade *bool `json:"enable_patch_version_auto_upgrade,omitempty"`

	// KubeVersion KubeVersion represents the needed Kubernetes version of the cluster.
	// It should be in x.y.z format.
	KubeVersion string `json:"kube_version"`

	// KubernetesOptions Additional k8s options such as pod security policy,
	// feature gates, etc.
	KubernetesOptions *KubernetesOptions `json:"kubernetes_options,omitempty"`

	// MaintenanceWindowStart MaintenanceWindowStart represents UTC time of when the cluster will start its maintenance tasks.
	// It should be in hh:mm:ss format if provided.
	MaintenanceWindowStart string `json:"maintenance_window_start"`

	// Name Name represents the desired name of the cluster.
	// It must not exceed 32 characters and can contain Latin letters,
	// with digits and hyphens. Must start with a letter or a digit.
	Name string `json:"name"`

	// NetworkId NetworkID contains a reference to the network of the cluster.
	// It can be set in cases where the network is pre-created.
	NetworkId string `json:"network_id"`

	// NetworkType NetworkType indicates which network will be used for master-node
	// connection.
	NetworkType string `json:"network_type"`

	// Pool Pool where the cluster master nodes are located.
	Pool string `json:"pool"`

	// PrivateKubeApi PrivateKubeAPI specifies whether kube API should be available from the Internet or not.
	// False by default.
	PrivateKubeApi bool `json:"private_kube_api"`

	// SubnetId SubnetID contains a reference to the subnet of the cluster.
	// It can be set in cases where the subnet is pre-created.
	SubnetId string `json:"subnet_id"`
}

// ClusterCreateStructClusterType The type of the cluster. If not specified,
// defaults based on the 'basic' field: basic=true → BASIC,
// basic=false → HIGH_AVAILABILITY. For HIGH_AVAILABILITY_MULTI_AZ
// clusters this field is required.
type ClusterCreateStructClusterType string

// ClusterDetailed Provides detailed information about cluster.
type ClusterDetailed struct {
	// Basic Specifies that cluster has only a single master and that control plane is not in highly available mode.
	Basic bool `json:"basic"`

	// ClusterType The type of the cluster.
	ClusterType ClusterDetailedClusterType `json:"cluster_type"`

	// CniCiliumSettings Settings for Cilium CNI if this CNI was chosen as "cni_type".
	// Otherwise settings will be ignored.
	CniCiliumSettings *CNICiliumSettings `json:"cni_cilium_settings,omitempty"`

	// CniType CNI type represents type of CNI which is used in cluster.
	CniType ClusterDetailedCniType `json:"cni_type"`

	// CreatedAt Timestamp in UTC timezone of when the cluster has been created.
	CreatedAt time.Time `json:"created_at"`

	// EnableAutorepair Reflects whether worker nodes are allowed to be reinstalled automatically in case of their unavailability or unhealthiness.
	EnableAutorepair bool `json:"enable_autorepair"`

	// EnablePatchVersionAutoUpgrade Specifies whether Kubernetes version of the cluster is allowed to be upgraded automatically.
	EnablePatchVersionAutoUpgrade bool `json:"enable_patch_version_auto_upgrade"`

	// Id Unique identifier of the cluster.
	Id string `json:"id"`

	// KubeApiIp The IP of the Kubernetes API.
	KubeApiIp string `json:"kube_api_ip"`

	// KubeVersion The current Kubernetes version of the cluster.
	KubeVersion string `json:"kube_version"`

	// KubernetesOptions Additional k8s options such as pod security policy,
	// feature gates, etc.
	KubernetesOptions KubernetesOptions `json:"kubernetes_options"`

	// MaintenanceLastStart MaintenanceLastStart is the timestamp in UTC timezone of the last cluster maintenance start.
	MaintenanceLastStart time.Time `json:"maintenance_last_start"`

	// MaintenanceWindowEnd MaintenanceWindowEnd represents the UTC time in the "hh:mm:ss"  format indicating when the cluster maintenance window ends.
	MaintenanceWindowEnd string `json:"maintenance_window_end"`

	// MaintenanceWindowStart MaintenanceWindowStart represents the UTC time in the "hh:mm:ss"  format indicating when the cluster maintenance window starts.
	MaintenanceWindowStart string `json:"maintenance_window_start"`

	// Name The name of the cluster.
	Name string `json:"name"`

	// NetworkId Contains reference to the network of the cluster.
	NetworkId string `json:"network_id"`

	// NetworkType Type of network l3vpn or standard.
	NetworkType ClusterDetailedNetworkType `json:"network_type"`

	// PkiTreeUpdatedAt PKITreeUpdatedAt represents the timestamp in UTC timezone of when the PKI-tree of the cluster was updated.
	PkiTreeUpdatedAt time.Time `json:"pki_tree_updated_at"`

	// Pool The pool of where the cluster master nodes are located.
	Pool string `json:"pool"`

	// PrivateKubeApi Whether kube API is available from the Internet or not.
	PrivateKubeApi bool `json:"private_kube_api"`

	// ProjectId Contains reference to the project of the cluster.
	ProjectId string `json:"project_id"`

	// Status Current status of the cluster.
	Status ClusterDetailedStatus `json:"status"`

	// SubnetId Contains reference to the subnet of the cluster.
	SubnetId string `json:"subnet_id"`

	// UpdatedAt Timestamp in UTC timezone of when the cluster has been updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// ClusterDetailedClusterType The type of the cluster.
type ClusterDetailedClusterType string

// ClusterDetailedCniType CNI type represents type of CNI which is used in cluster.
type ClusterDetailedCniType string

// ClusterDetailedNetworkType Type of network l3vpn or standard.
type ClusterDetailedNetworkType string

// ClusterDetailedStatus Current status of the cluster.
type ClusterDetailedStatus string

// ClusterList List of clusters.
type ClusterList struct {
	Clusters *[]Cluster `json:"clusters,omitempty"`
}

// ClusterResp Cluster response.
type ClusterResp struct {
	// Cluster Provides detailed information about cluster.
	Cluster *ClusterDetailed `json:"cluster,omitempty"`
}

// ClusterUpdateBody ClusterUpdateBody
// represents body content.
type ClusterUpdateBody struct {
	Cluster *ClusterUpdateStruct `json:"cluster,omitempty"`
}

// ClusterUpdateStruct defines model for ClusterUpdateStruct.
type ClusterUpdateStruct struct {
	// CniCiliumSettings Settings for Cilium CNI if this CNI was chosen as "cni_type".
	// Otherwise settings will be ignored.
	CniCiliumSettings *CNICiliumSettings `json:"cni_cilium_settings,omitempty"`

	// EnableAutorepair EnableAutorepair reflects whether worker nodes are allowed to be reinstalled  automatically in case of their unavailability or unhealthiness.
	EnableAutorepair *bool `json:"enable_autorepair,omitempty"`

	// EnablePatchVersionAutoUpgrade EnablePatchVersionAutoUpgrade specifies if Kubernetes version of the cluster is allowed to be upgraded
	// automatically.
	// Enabled by default for regional clusters and disabled for zonal clusters.
	EnablePatchVersionAutoUpgrade *bool `json:"enable_patch_version_auto_upgrade,omitempty"`

	// KubernetesOptions Additional k8s options such as pod security policy,
	// feature gates, etc.
	KubernetesOptions *KubernetesOptions `json:"kubernetes_options,omitempty"`

	// MaintenanceWindowStart MaintenanceWindowStart represents UTC time of when the cluster will start its maintenance tasks.
	// It should be in hh:mm:ss format if provided.
	MaintenanceWindowStart *string `json:"maintenance_window_start,omitempty"`
}

// ClustersLimits defines model for ClustersLimits.
type ClustersLimits struct {
	// BasicClustersLimit The minimum number of basic clusters in project.
	BasicClustersLimit int `json:"basic_clusters_limit"`

	// HighAvailabilityClustersLimit The maximum number of high-availability clusters in project.
	HighAvailabilityClustersLimit int `json:"high_availability_clusters_limit"`

	// HighAvailabilityMultiAzClustersLimit Represents the maximum number of high-availability multi-AZ clusters in project.
	HighAvailabilityMultiAzClustersLimit int `json:"high_availability_multi_az_clusters_limit"`
}

// ControlPlaneLogging Control plane logging settings.
type ControlPlaneLogging struct {
	// Components Control plane components from which logs collection should be enabled.
	Components *[]string `json:"components,omitempty"`

	// Group Cloud logging group name. The s/mks/ prefix will be automatically prepended to the specified value.
	Group *string `json:"group,omitempty"`
}

// ControlPlaneLoggingUpdateBody Control plane logging settings which should be updated.
type ControlPlaneLoggingUpdateBody struct {
	// Components Control plane components from which logs collection should be enabled.
	Components *[]string `json:"components,omitempty"`
}

// DedicatedNodegroupConfig Configuration for dedicated based node groups.
type DedicatedNodegroupConfig struct {
	// CreateStoragePartition Determines is storage partition should be created on fastest disk.
	CreateStoragePartition *bool `json:"create_storage_partition,omitempty"`

	// Currency Which balance will be used to order new servers.
	// ## Note 💡
	// ```
	// main - to use main balance. This option will be used as default.
	// bonus - to use bonus balance.
	// ```
	Currency      *DedicatedNodegroupConfigCurrency `json:"currency,omitempty"`
	PricePlanUuid string                            `json:"price_plan_uuid"`

	// RootSizeGb RootSizeGB represents size of "/" partition on dedicated nodes.
	RootSizeGb  *int64 `json:"root_size_gb,omitempty"`
	ServiceUuid string `json:"service_uuid"`
}

// DedicatedNodegroupConfigCurrency Which balance will be used to order new servers.
// ## Note 💡
// ```
// main - to use main balance. This option will be used as default.
// bonus - to use bonus balance.
// ```
type DedicatedNodegroupConfigCurrency string

// ExtendedWorkerNodeLimits defines model for ExtendedWorkerNodeLimits.
type ExtendedWorkerNodeLimits struct {
	// CpuDriveCoefficient Calculation coefficient for local drives relative to the number of CPUs.
	// The final limit will be calculated using the formula: cpu_number * cpu_drive_coefficient
	CpuDriveCoefficient *int `json:"cpu_drive_coefficient,omitempty"`

	// CpuRamCoefficient Calculation coefficient for RAM size relative to the number of CPUs.
	// The final limit is calculated by the formula: cpu_number * cpu_ram_coefficient
	CpuRamCoefficient *int `json:"cpu_ram_coefficient,omitempty"`

	// MaxLocalDriveGbPerNode Maximum local volume size in gigabytes for each worker node.
	// For network volumes, the default limits will be used.
	MaxLocalDriveGbPerNode *int `json:"max_local_drive_gb_per_node,omitempty"`

	// MaxRamMbPerNode Maximum RAM size for each worker node in megabytes.
	MaxRamMbPerNode *int `json:"max_ram_mb_per_node,omitempty"`

	// MinLocalDriveGbPerNode Minimum local volume size in gigabytes for each worker node.
	// For network volumes, the default limits will be used.
	MinLocalDriveGbPerNode *int `json:"min_local_drive_gb_per_node,omitempty"`

	// MinRamMbPerNode Minimum RAM size in megabytes for each worker node.
	MinRamMbPerNode *int `json:"min_ram_mb_per_node,omitempty"`
}

// FeatureGatesList List of available feature gates.
type FeatureGatesList struct {
	FeatureGates *[]AvailableFeatureGates `json:"feature_gates,omitempty"`
}

// KubeVersionInfo Kubernetes version information.
type KubeVersionInfo struct {
	// Version Supported Kubernetes version in format: "X.Y.Z"
	Version *string `json:"version,omitempty"`

	// IsDefault Flag indicates whether the Kubernetes version is default.
	IsDefault *bool `json:"is_default,omitempty"`
}

// KubeVersionsList List of supported Kubernetes versions.
type KubeVersionsList struct {
	KubeVersions *[]KubeVersionInfo `json:"kube_versions,omitempty"`
}

// KubernetesOptions Additional k8s options such as pod security policy,
// feature gates, etc.
type KubernetesOptions struct {
	// AdmissionControllers Turned on admission controllers for the cluster.
	AdmissionControllers []string  `json:"admission_controllers"`
	AuditLogs            AuditLogs `json:"audit_logs"`

	// FeatureGates Turned on feature gates
	FeatureGates []string `json:"feature_gates"`

	// Oidc OIDC represents parameters to connect client's OIDC provider with Kubernetes.
	Oidc OIDC `json:"oidc"`

	// X509CaCertificates Represent custom X509 CA certificates which can be used for cluster components. Certificates should be encoded to base64 format. Note 💡 ``` X509CaCertificates can be disabled for some pools. ```
	X509CaCertificates string `json:"x509_ca_certificates,omitempty"`
}

// LimitsList Default limits list
type LimitsList struct {
	Cluster ClustersLimits `json:"cluster"`

	// ExtendedLimits Flexible limits rules.
	ExtendedLimits *map[string]ExtendedWorkerNodeLimits `json:"extended_limits,omitempty"`
	Nodegroup      NodegroupLimits                      `json:"nodegroup"`
	WorkerNode     WorkerNodeLimits                     `json:"worker_node"`
}

// LogComponent Available component for control plane logs collection.
type LogComponent struct {
	// Description Reason explains the purpose of the component.
	Description string `json:"description"`

	// Name Component name.
	Name string `json:"name"`
}

// LogComponentsList List of available log components.
type LogComponentsList struct {
	Components *[]LogComponent `json:"components,omitempty"`
}

// Node Provides information about node.
type Node struct {
	// CreatedAt Timestamp in UTC timezone of when the node has been created.
	CreatedAt time.Time `json:"created_at"`

	// Hostname A hostname of the node.
	Hostname string `json:"hostname"`

	// Id Unique identifier of the node.
	Id string `json:"id"`

	// Ip IP address of the node.
	Ip string `json:"ip"`

	// NodegroupId Contains node group identifier.
	NodegroupId string `json:"nodegroup_id"`

	// ProviderServerId Contains server identifier in external provider (OpenStack, dedicated resource).
	ProviderServerId string `json:"provider_server_id"`

	// UpdatedAt Timestamp in UTC timezone of when the node has been updated.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// NodeResp Node response.
type NodeResp struct {
	// Node Provides information about node.
	Node Node `json:"node"`
}

// NodegroupActions defines model for NodegroupActions.
type NodegroupActions struct {
	Delete                  Action `json:"delete"`
	DeleteNode              Action `json:"delete_node"`
	ReinstallNode           Action `json:"reinstall_node"`
	Resize                  Action `json:"resize"`
	UpdateAutoscalingMinMax Action `json:"update_autoscaling_min_max"`
	UpdateLabels            Action `json:"update_labels"`
	UpdateTaints            Action `json:"update_taints"`
}

// NodegroupActionsResp Available actions of the nodegroup.
type NodegroupActionsResp struct {
	Actions *NodegroupActions `json:"actions,omitempty"`
}

// NodegroupAdditionalInfo Provides additional information about node group like userdata, etc.
type NodegroupAdditionalInfo struct {
	// UserData True when node group has user_data field filled.
	UserData bool `json:"user_data"`
}

// NodegroupCreateStruct defines model for NodegroupCreateStruct.
type NodegroupCreateStruct struct {
	// AutoscaleMaxNodes Maximum possible number of worker nodes in the node group.
	AutoscaleMaxNodes *int64 `json:"autoscale_max_nodes,omitempty"`

	// AutoscaleMinNodes Minimum possible number of worker nodes in the node group.
	AutoscaleMinNodes *int64 `json:"autoscale_min_nodes,omitempty"`

	// Cidr CIDR for node group specified by client.
	Cidr string `json:"cidr,omitempty"`

	// CloudNodegroupConfig Configuration of cloud-based node groups.
	CloudNodegroupConfig *CloudNodegroupConfig `json:"cloud_nodegroup_config,omitempty"`

	// Count Node count for this node group.
	Count int64 `json:"count"`

	// DedicatedNodegroupConfig Configuration for dedicated based node groups.
	DedicatedNodegroupConfig *DedicatedNodegroupConfig `json:"dedicated_nodegroup_config,omitempty"`

	// EnableAutoscale Indicates whether the node group is allowed to be scaled automatically.
	EnableAutoscale *bool `json:"enable_autoscale,omitempty"`

	// InstallNvidiaDevicePlugin Indicates whether NVIDIA device plugin installation was requested. Applicable only for node groups with GPU nodes.
	InstallNvidiaDevicePlugin *bool `json:"install_nvidia_device_plugin,omitempty"`

	// Labels An object containing a set of Kubernetes labels that will be applied for each node in the group. The keys must be user-defined.
	Labels *map[string]string `json:"labels,omitempty"`

	// Preemptible Indicates whether nodes in the node group are preemptible.
	Preemptible bool `json:"preemptible,omitempty"`

	// Segment Should contain the valid segment name where node group nodes will be created.
	Segment string `json:"segment"`

	// Taints List of node group taints.
	Taints *[]NodegroupTaint `json:"taints,omitempty"`

	// UserData Base64 data which is used to pass a script that worker nodes run on boot.
	UserData string `json:"user_data,omitempty"`
}

// NodegroupDetailed defines model for NodegroupDetailed.
type NodegroupDetailed struct {
	// AutoscaleMaxNodes Maximum number of worker nodes in the node group.
	AutoscaleMaxNodes *int64 `json:"autoscale_max_nodes,omitempty"`

	// AutoscaleMinNodes Minimum number of worker nodes in the node group.
	AutoscaleMinNodes *int64 `json:"autoscale_min_nodes,omitempty"`

	// Cidr A CIDR for node group specified by client.
	Cidr *string `json:"cidr,omitempty"`

	// CloudNodegroupConfig Configuration of cloud-based node groups in response.
	CloudNodegroupConfig *CloudNodegroupConfigInfo `json:"cloud_nodegroup_config,omitempty"`

	// ClusterId Unique identifier of the cluster.
	ClusterId string `json:"cluster_id"`

	// CreatedAt Timestamp in UTC timezone of when the node group has been created.
	CreatedAt time.Time `json:"created_at"`

	// DedicatedNodegroupConfig Configuration for dedicated based node groups.
	DedicatedNodegroupConfig *DedicatedNodegroupConfig `json:"dedicated_nodegroup_config,omitempty"`

	// EnableAutoscale Indicates whether the node group is allowed to be scaled automatically.
	EnableAutoscale bool `json:"enable_autoscale"`

	// Id Unique identifier of the node group.
	Id string `json:"id"`

	// InstallNvidiaDevicePlugin Indicates whether NVIDIA device plugin installation was requested. Applicable only for node groups with GPU nodes.
	InstallNvidiaDevicePlugin bool `json:"install_nvidia_device_plugin"`

	// Labels An object containing a set of Kubernetes labels that will be applied for each node in the group. The keys must be user-defined.
	Labels map[string]string `json:"labels"`

	// NodegroupType Type of the nodes in node group. ## Note 💡 ` STANDARD      -- for all nodes from configs: Standard line, CPU line and Memory line; GPU           -- for cloud nodes from GPU line; DEDICATED     -- for dedicated nodes; DEDICATED_GPU -- for dedicated nodes from GPU line; `
	NodegroupType NodegroupDetailedNodegroupType `json:"nodegroup_type"`

	// Nodes List of all nodes in the node group.
	Nodes []Node `json:"nodes"`

	// Preemptible Indicates whether nodes in the node group are preemptible.
	Preemptible bool `json:"preemptible"`

	// Segment Pool segment for all nodes in the node group.
	Segment string `json:"segment"`

	// Status Current status of the node group.
	Status NodegroupDetailedStatus `json:"status"`

	// Taints A list of node group taints.
	Taints []NodegroupTaint `json:"taints"`

	// UpdateStrategy Update strategy for worker nodes in the node group.
	UpdateStrategy NodegroupUpdateStrategy `json:"update_strategy"`

	// UpdatedAt Timestamp in UTC timezone of when the node group has been updated.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`

	// UserData Base64 data which is used to pass a script that worker nodes run on boot.
	UserData string `json:"user_data,omitempty"`
}

// NodegroupDetailedNodegroupType Type of the nodes in node group. ## Note 💡 ` STANDARD      -- for all nodes from configs: Standard line, CPU line and Memory line; GPU           -- for cloud nodes from GPU line; DEDICATED     -- for dedicated nodes; DEDICATED_GPU -- for dedicated nodes from GPU line; `
type NodegroupDetailedNodegroupType string

// NodegroupDetailedStatus Current status of the node group.
type NodegroupDetailedStatus string

// NodegroupInfo Provides detailed information about node group.
type NodegroupInfo struct {
	// AutoscaleMaxNodes Maximum number of worker nodes in the node group.
	AutoscaleMaxNodes *int64 `json:"autoscale_max_nodes,omitempty"`

	// AutoscaleMinNodes Minimum number of worker nodes in the node group.
	AutoscaleMinNodes *int64 `json:"autoscale_min_nodes,omitempty"`

	// Cidr A CIDR for node group specified by client.
	Cidr *string `json:"cidr,omitempty"`

	// CloudNodegroupConfig Configuration of cloud-based node groups in response.
	CloudNodegroupConfig *CloudNodegroupConfigInfo `json:"cloud_nodegroup_config,omitempty"`

	// ClusterId Unique identifier of the cluster.
	ClusterId string `json:"cluster_id"`

	// CreatedAt Timestamp in UTC timezone of when the node group has been created.
	CreatedAt time.Time `json:"created_at"`

	// DedicatedNodegroupConfig Configuration for dedicated based node groups.
	DedicatedNodegroupConfig *DedicatedNodegroupConfig `json:"dedicated_nodegroup_config,omitempty"`

	// EnableAutoscale Indicates whether the node group is allowed to be scaled automatically.
	EnableAutoscale bool `json:"enable_autoscale"`

	// Id Unique identifier of the node group.
	Id string `json:"id"`

	// InstallNvidiaDevicePlugin Indicates whether NVIDIA device plugin installation was requested. Applicable only for node groups with GPU nodes.
	InstallNvidiaDevicePlugin bool `json:"install_nvidia_device_plugin"`

	// Labels An object containing a set of Kubernetes labels that will be applied for each node in the group. The keys must be user-defined.
	Labels map[string]string `json:"labels"`

	// NodegroupType Type of the nodes in node group. ## Note 💡 ` STANDARD      -- for all nodes from configs: Standard line, CPU line and Memory line; GPU           -- for cloud nodes from GPU line; DEDICATED     -- for dedicated nodes; DEDICATED_GPU -- for dedicated nodes from GPU line; `
	NodegroupType NodegroupInfoNodegroupType `json:"nodegroup_type"`

	// Nodes List of all nodes in the node group.
	Nodes []Node `json:"nodes"`

	// Preemptible Indicates whether nodes in the node group are preemptible.
	Preemptible bool `json:"preemptible"`

	// Segment Pool segment for all nodes in the node group.
	Segment string `json:"segment"`

	// Status Current status of the node group.
	Status NodegroupInfoStatus `json:"status"`

	// Taints A list of node group taints.
	Taints []NodegroupTaint `json:"taints"`

	// UpdateStrategy Update strategy for worker nodes in the node group.
	UpdateStrategy NodegroupUpdateStrategy `json:"update_strategy"`

	// UpdatedAt Timestamp in UTC timezone of when the node group has been updated.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// NodegroupInfoNodegroupType Type of the nodes in node group. ## Note 💡 ` STANDARD      -- for all nodes from configs: Standard line, CPU line and Memory line; GPU           -- for cloud nodes from GPU line; DEDICATED     -- for dedicated nodes; DEDICATED_GPU -- for dedicated nodes from GPU line; `
type NodegroupInfoNodegroupType string

// NodegroupInfoStatus Current status of the node group.
type NodegroupInfoStatus string

// NodegroupLimits defines model for NodegroupLimits.
type NodegroupLimits struct {
	// MaxNodegroupsPerPool Maximum number of nodegroups in the pool.
	MaxNodegroupsPerPool int `json:"max_nodegroups_per_pool"`

	// MaxNodesPerNodegroup The maximum number of nodes in nodegroup.
	MaxNodesPerNodegroup int `json:"max_nodes_per_nodegroup"`

	// MinNodesPerDedicatedNodegroup The minimum number of nodes in dedicated nodegroup.
	MinNodesPerDedicatedNodegroup int `json:"min_nodes_per_dedicated_nodegroup"`

	// MinNodesPerNodegroup The minimum number of nodes in nodegroup.
	MinNodesPerNodegroup int `json:"min_nodes_per_nodegroup"`
}

// NodegroupList List of node groups in the cluster.
type NodegroupList struct {
	Nodegroups []NodegroupListItem `json:"nodegroups"`
}

// NodegroupListItem defines model for NodegroupListItem.
type NodegroupListItem struct {
	// AutoscaleMaxNodes Maximum number of worker nodes in the node group.
	AutoscaleMaxNodes *int64 `json:"autoscale_max_nodes,omitempty"`

	// AutoscaleMinNodes Minimum number of worker nodes in the node group.
	AutoscaleMinNodes *int64 `json:"autoscale_min_nodes,omitempty"`

	// AvailableAdditionalInfo Provides additional information about node group like userdata, etc.
	AvailableAdditionalInfo NodegroupAdditionalInfo `json:"available_additional_info"`

	// Cidr A CIDR for node group specified by client.
	Cidr *string `json:"cidr,omitempty"`

	// CloudNodegroupConfig Configuration of cloud-based node groups in response.
	CloudNodegroupConfig *CloudNodegroupConfigInfo `json:"cloud_nodegroup_config,omitempty"`

	// ClusterId Unique identifier of the cluster.
	ClusterId string `json:"cluster_id"`

	// CreatedAt Timestamp in UTC timezone of when the node group has been created.
	CreatedAt time.Time `json:"created_at"`

	// DedicatedNodegroupConfig Configuration for dedicated based node groups.
	DedicatedNodegroupConfig *DedicatedNodegroupConfig `json:"dedicated_nodegroup_config,omitempty"`

	// EnableAutoscale Indicates whether the node group is allowed to be scaled automatically.
	EnableAutoscale bool `json:"enable_autoscale"`

	// Id Unique identifier of the node group.
	Id string `json:"id"`

	// InstallNvidiaDevicePlugin Indicates whether NVIDIA device plugin installation was requested. Applicable only for node groups with GPU nodes.
	InstallNvidiaDevicePlugin bool `json:"install_nvidia_device_plugin"`

	// Labels An object containing a set of Kubernetes labels that will be applied for each node in the group. The keys must be user-defined.
	Labels map[string]string `json:"labels"`

	// NodegroupType Type of the nodes in node group. ## Note 💡 ` STANDARD      -- for all nodes from configs: Standard line, CPU line and Memory line; GPU           -- for cloud nodes from GPU line; DEDICATED     -- for dedicated nodes; DEDICATED_GPU -- for dedicated nodes from GPU line; `
	NodegroupType NodegroupListItemNodegroupType `json:"nodegroup_type"`

	// Nodes List of all nodes in the node group.
	Nodes []Node `json:"nodes"`

	// Preemptible Indicates whether nodes in the node group are preemptible.
	Preemptible bool `json:"preemptible"`

	// Segment Pool segment for all nodes in the node group.
	Segment string `json:"segment"`

	// Status Current status of the node group.
	Status NodegroupListItemStatus `json:"status"`

	// Taints A list of node group taints.
	Taints []NodegroupTaint `json:"taints"`

	// UpdateStrategy Update strategy for worker nodes in the node group.
	UpdateStrategy NodegroupUpdateStrategy `json:"update_strategy"`

	// UpdatedAt Timestamp in UTC timezone of when the node group has been updated.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// NodegroupListItemNodegroupType Type of the nodes in node group. ## Note 💡 ` STANDARD      -- for all nodes from configs: Standard line, CPU line and Memory line; GPU           -- for cloud nodes from GPU line; DEDICATED     -- for dedicated nodes; DEDICATED_GPU -- for dedicated nodes from GPU line; `
type NodegroupListItemNodegroupType string

// NodegroupListItemStatus Current status of the node group.
type NodegroupListItemStatus string

// NodegroupResizeBody Request Body schema.
type NodegroupResizeBody struct {
	Nodegroup NodegroupResizeStruct `json:"nodegroup"`
}

// NodegroupResizeStruct defines model for NodegroupResizeStruct.
type NodegroupResizeStruct struct {
	// Desired Desired number of nodes in the node group.
	Desired int64 `json:"desired"`
}

// NodegroupResp Node group response.
type NodegroupResp struct {
	// Nodegroup Provides detailed information about node group.
	Nodegroup NodegroupDetailed `json:"nodegroup"`
}

// NodegroupTaint K8s node group taint that applies for every node in the group.
type NodegroupTaint struct {
	// Effect Effect for taint.
	Effect NodegroupTaintEffect `json:"effect"`

	// Key Key for taint.
	Key string `json:"key"`

	// Value Value for taint.
	Value string `json:"value"`
}

// NodegroupTaintEffect Effect for taint.
type NodegroupTaintEffect string

// NodegroupUpdateBody Request Body schema.
type NodegroupUpdateBody struct {
	Nodegroup NodegroupUpdateStruct `json:"nodegroup"`
}

// NodegroupUpdateStrategy Update strategy for worker nodes in the node group.
type NodegroupUpdateStrategy struct {
	// Method Mechanism used to update worker nodes.
	Method NodegroupUpdateStrategyMethod `json:"method"`
}

// NodegroupUpdateStrategyMethod Mechanism used to update worker nodes.
type NodegroupUpdateStrategyMethod string

// NodegroupUpdateStruct defines model for NodegroupUpdateStruct.
type NodegroupUpdateStruct struct {
	// AutoscaleMaxNodes Maximum number of worker nodes in the cloud-based node group.
	AutoscaleMaxNodes *int `json:"autoscale_max_nodes,omitempty"`

	// AutoscaleMinNodes Minimum number of worker nodes in the cloud-based node group.
	AutoscaleMinNodes *int `json:"autoscale_min_nodes,omitempty"`

	// EnableAutoscale Indicates whether the cloud node group is allowed to be scaled automatically.
	EnableAutoscale *bool `json:"enable_autoscale,omitempty"`

	// Labels An object containing a set of Kubernetes labels that will be applied for each node in the group. The keys must be user-defined.
	Labels *map[string]string `json:"labels,omitempty"`

	// Taints List of node group taints.
	Taints *[]NodegroupTaint `json:"taints,omitempty"`
}

// NodegroupsCreateBody Request Body schema for creating multiple node groups.
type NodegroupsCreateBody struct {
	Nodegroups []NodegroupCreateStruct `json:"nodegroups"`
}

// OIDC OIDC represents parameters to connect client's OIDC provider with Kubernetes.
type OIDC struct {
	// CaCerts CACerts represent optional custom CA certs chain in X509 PEM format of provider's SSL certificate.
	// Will be written to file on masters which will be passed in `--oidc-ca-file` kube-apiserver flag.
	CaCerts string `json:"ca_certs,omitempty"`

	// CaCertsExpiration CACertsExpiration represents date and time when the first of provided CA certificates will be expired.
	CaCertsExpiration *time.Time `json:"ca_certs_expiration,omitempty"`

	// ClientId Required client id that all tokens must be issued for. Will be placed in `--oidc-client-id` flag. It is required when enabled = true.
	ClientId string `json:"client_id"`

	// Enabled If `enabled` OIDC should be turned on in the cluster.
	// False by default.
	Enabled bool `json:"enabled"`

	// GroupsClaim Optional JWT claim to use as the user's group. By default, `groups`. Will be placed in `--oidc-groups-claim` flag.
	GroupsClaim string `json:"groups_claim"`

	// IssuerUrl URL of the provider that allows the API server to discover public signing keys. Will be placed in `--oidc-issuer-url` flag. It is required when enabled = true.
	IssuerUrl string `json:"issuer_url"`

	// ProviderName Custom user defined name of the provider. It is not used in the cluster directly. It is required when enabled = true.
	ProviderName string `json:"provider_name"`

	// UsernameClaim Optional JWT claim to use as the username. By default, `sub`. Will be placed in `--oidc-username-claim` flag.
	UsernameClaim string `json:"username_claim"`
}

// OptionNamesAC List of available admission controllers.
type OptionNamesAC = []string

// OptionNamesFG List of available feature gate names.
type OptionNamesFG = []string

// RegistriesIntegration Registries integration of the cluster.
type RegistriesIntegration struct {
	Registries []RegistryWithMeta `json:"registries"`

	// Status Status represents status of the registries' integration.
	Status RegistriesIntegrationStatus `json:"status"`
}

// RegistriesIntegrationStatus Status represents status of the registries' integration.
type RegistriesIntegrationStatus string

// RegistriesIntegrationCreateBody Body content.
type RegistriesIntegrationCreateBody struct {
	Registries []RegistriesIntegrationCreateStruct `json:"registries"`
}

// RegistriesIntegrationCreateStruct defines model for RegistriesIntegrationCreateStruct.
type RegistriesIntegrationCreateStruct struct {
	// Id Unique identifier of the registry.
	Id string `json:"id"`
}

// RegistriesIntegrationUpdateBody Body content.
type RegistriesIntegrationUpdateBody struct {
	Registries []RegistriesIntegrationUpdateStruct `json:"registries"`
}

// RegistriesIntegrationUpdateStruct defines model for RegistriesIntegrationUpdateStruct.
type RegistriesIntegrationUpdateStruct struct {
	// Id Unique identifier of the registry.
	Id string `json:"id"`
}

// RegistryWithMeta Registry integration with metadata.
type RegistryWithMeta struct {
	// Id Unique identifier of the registry.
	Id string `json:"id"`

	// Name Name of the registry.
	Name string `json:"name"`
}

// ResourceUsage Project resource usage.
type ResourceUsage struct {
	// ClustersCount Amount of clusters in the project
	ClustersCount *int64 `json:"clusters_count,omitempty"`

	// NodegroupsCount Number of node groups in the project.
	NodegroupsCount *int64 `json:"nodegroups_count,omitempty"`
}

// Task Provides information about task.
type Task struct {
	// ClusterId Contains cluster identifier.
	ClusterId string `json:"cluster_id"`

	// ErrorDetails Provides information about error details of the task. Disabled by default, to enable use query parameter 'withErrorDetails=true'.
	ErrorDetails *TaskErrorDetails `json:"error_details,omitempty"`

	// Id The identifier of the task.
	Id string `json:"id"`

	// NodegroupId Contains node group identifier.
	NodegroupId *string `json:"nodegroup_id,omitempty"`

	// StartedAt The timestamp in UTC timezone of when the task has been started.
	StartedAt time.Time `json:"started_at"`

	// Status Current status of the task.
	Status TaskStatus `json:"status"`

	// Type Task's type.
	Type string `json:"type"`

	// UpdatedAt The timestamp in UTC timezone of when the task has been updated.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// TaskStatus Current status of the task.
type TaskStatus string

// TaskErrorDetails Provides information about error details of the task. Disabled by default, to enable use query parameter 'withErrorDetails=true'.
type TaskErrorDetails struct {
	// Code Task's error code.
	Code int64 `json:"code"`

	// Details Contains task's error helpful information.
	Details *string `json:"details,omitempty"`

	// Name Task's error short description.
	Name string `json:"name"`
}

// TaskList Provides information about tasks of the cluster.
type TaskList struct {
	// Count Count of all tasks of the cluster.
	Count int64  `json:"count"`
	Tasks []Task `json:"tasks"`
}

// TaskResp Provides information about task of the cluster.
type TaskResp struct {
	// Task Provides information about task.
	Task Task `json:"task"`
}

// WorkerNodeLimits defines model for WorkerNodeLimits.
type WorkerNodeLimits struct {
	// MaxCpusPerNode The maximum number of CPUs for each worker node.
	MaxCpusPerNode int `json:"max_cpus_per_node"`

	// MaxRamMbPerNode Maximum RAM size in megabytes for each worker node.
	MaxRamMbPerNode int `json:"max_ram_mb_per_node"`

	// MaxVolumeGbPerNode Maximum volume size in gigabytes for each worker node.
	MaxVolumeGbPerNode int `json:"max_volume_gb_per_node"`

	// MinCpusPerNode The minimum number of CPUs for each worker node.
	MinCpusPerNode int `json:"min_cpus_per_node"`

	// MinRamMbPerNode Minimum RAM size in megabytes for each worker node.
	MinRamMbPerNode int `json:"min_ram_mb_per_node"`

	// MinVolumeGbPerNode Minimum volume size in gigabytes for each worker node.
	MinVolumeGbPerNode int `json:"min_volume_gb_per_node"`
}

// GenericError Generic Error.
type GenericError struct {
	Error struct {
		// Message Error Message.
		Message string `json:"message"`
	} `json:"error"`
}

// GenericNotFoundError Generic message about not found error for any object.
type GenericNotFoundError struct {
	Error struct {
		// Id Object ID.
		Id string `json:"id"`

		// Message Message of the error.
		Message string `json:"message"`
	} `json:"error"`
}

// ClusterId defines model for cluster_id.
type ClusterId = string

// KubeVersion defines model for kube_version.
type KubeVersion = string

// Lang defines model for lang.
type Lang string

// Limit defines model for limit.
type Limit = uint64

// NodeId defines model for node_id.
type NodeId = string

// NodegroupId defines model for nodegroup_id.
type NodegroupId = string

// Offset defines model for offset.
type Offset = uint64

// RegistryId defines model for registry_id.
type RegistryId = string

// TaskId defines model for task_id.
type TaskId = string

// WithErrorDetails defines model for with_error_details.
type WithErrorDetails = bool

// GetClusterActionsV2Params defines parameters for GetClusterActionsV2.
type GetClusterActionsV2Params struct {
	// Lang Language on which response should be returned.
	Lang *GetClusterActionsV2ParamsLang `form:"lang,omitempty" json:"lang,omitempty"`
}

// GetClusterActionsV2ParamsLang defines parameters for GetClusterActionsV2.
type GetClusterActionsV2ParamsLang string

// GetNodegroupActionsV2Params defines parameters for GetNodegroupActionsV2.
type GetNodegroupActionsV2Params struct {
	// Lang Language on which response should be returned.
	Lang *GetNodegroupActionsV2ParamsLang `form:"lang,omitempty" json:"lang,omitempty"`
}

// GetNodegroupActionsV2ParamsLang defines parameters for GetNodegroupActionsV2.
type GetNodegroupActionsV2ParamsLang string

// ListTasksV2Params defines parameters for ListTasksV2.
type ListTasksV2Params struct {
	// Limit Limit of elements in response.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of elements to skip.
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`

	// WithErrorDetails Flag to show error details at task view.
	WithErrorDetails *WithErrorDetails `form:"with_error_details,omitempty" json:"with_error_details,omitempty"`
}

// GetTaskV2Params defines parameters for GetTaskV2.
type GetTaskV2Params struct {
	// WithErrorDetails Flag to show error details at task view.
	WithErrorDetails *WithErrorDetails `form:"with_error_details,omitempty" json:"with_error_details,omitempty"`
}

// GetLimitsV2Params defines parameters for GetLimitsV2.
type GetLimitsV2Params struct {
	// KubeVersion Version of Kubernetes for which response should be returned.
	KubeVersion *KubeVersion `form:"kube_version,omitempty" json:"kube_version,omitempty"`
}

// ListLogComponentsV2Params defines parameters for ListLogComponentsV2.
type ListLogComponentsV2Params struct {
	// Lang Language on which response should be returned.
	Lang *ListLogComponentsV2ParamsLang `form:"lang,omitempty" json:"lang,omitempty"`
}

// ListLogComponentsV2ParamsLang defines parameters for ListLogComponentsV2.
type ListLogComponentsV2ParamsLang string

// CreateClusterV2JSONRequestBody defines body for CreateClusterV2 for application/json ContentType.
type CreateClusterV2JSONRequestBody = ClusterCreateBody

// PatchClusterV2JSONRequestBody defines body for PatchClusterV2 for application/json ContentType.
type PatchClusterV2JSONRequestBody = ClusterUpdateBody

// UpdateClusterV2JSONRequestBody defines body for UpdateClusterV2 for application/json ContentType.
type UpdateClusterV2JSONRequestBody = ClusterUpdateBody

// InitControlPlaneLoggingV2JSONRequestBody defines body for InitControlPlaneLoggingV2 for application/json ContentType.
type InitControlPlaneLoggingV2JSONRequestBody = ControlPlaneLogging

// UpdateControlPlaneLoggingV2JSONRequestBody defines body for UpdateControlPlaneLoggingV2 for application/json ContentType.
type UpdateControlPlaneLoggingV2JSONRequestBody = ControlPlaneLoggingUpdateBody

// CreateNodegroupsV2JSONRequestBody defines body for CreateNodegroupsV2 for application/json ContentType.
type CreateNodegroupsV2JSONRequestBody = NodegroupsCreateBody

// PatchNodegroupV2JSONRequestBody defines body for PatchNodegroupV2 for application/json ContentType.
type PatchNodegroupV2JSONRequestBody = NodegroupUpdateBody

// PutNodegroupV2JSONRequestBody defines body for PutNodegroupV2 for application/json ContentType.
type PutNodegroupV2JSONRequestBody = NodegroupUpdateBody

// ResizeNodegroupV2JSONRequestBody defines body for ResizeNodegroupV2 for application/json ContentType.
type ResizeNodegroupV2JSONRequestBody = NodegroupResizeBody

// CreateRegistriesV2JSONRequestBody defines body for CreateRegistriesV2 for application/json ContentType.
type CreateRegistriesV2JSONRequestBody = RegistriesIntegrationCreateBody

// UpdateRegistriesV2JSONRequestBody defines body for UpdateRegistriesV2 for application/json ContentType.
type UpdateRegistriesV2JSONRequestBody = RegistriesIntegrationUpdateBody
