// Code generated by mockery. DO NOT EDIT.

package mksclient

import (
	mksclient "github.com/selectel/mks-go/v2/pkg/mksclient"
	mock "github.com/stretchr/testify/mock"
)

// MockAPIError is an autogenerated mock type for the APIError type
type MockAPIError struct {
	mock.Mock
}

type MockAPIError_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPIError) EXPECT() *MockAPIError_Expecter {
	return &MockAPIError_Expecter{mock: &_m.Mock}
}

// ToMKSError provides a mock function with given fields: statusCode
func (_m *MockAPIError) ToMKSError(statusCode int) *mksclient.MKSError {
	ret := _m.Called(statusCode)

	if len(ret) == 0 {
		panic("no return value specified for ToMKSError")
	}

	var r0 *mksclient.MKSError
	if rf, ok := ret.Get(0).(func(int) *mksclient.MKSError); ok {
		r0 = rf(statusCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mksclient.MKSError)
		}
	}

	return r0
}

// MockAPIError_ToMKSError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToMKSError'
type MockAPIError_ToMKSError_Call struct {
	*mock.Call
}

// ToMKSError is a helper method to define mock.On call
//   - statusCode int
func (_e *MockAPIError_Expecter) ToMKSError(statusCode interface{}) *MockAPIError_ToMKSError_Call {
	return &MockAPIError_ToMKSError_Call{Call: _e.mock.On("ToMKSError", statusCode)}
}

func (_c *MockAPIError_ToMKSError_Call) Run(run func(statusCode int)) *MockAPIError_ToMKSError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockAPIError_ToMKSError_Call) Return(_a0 *mksclient.MKSError) *MockAPIError_ToMKSError_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAPIError_ToMKSError_Call) RunAndReturn(run func(int) *mksclient.MKSError) *MockAPIError_ToMKSError_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAPIError creates a new instance of MockAPIError. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPIError(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPIError {
	mock := &MockAPIError{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
